version: "3.1"

services:
  postgres:
    container_name: habit-maker-postgres
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "6000:5432"
    restart: always
    volumes:
      - habit-db:/var/lib/postgresql/data
  backend:
    container_name: habit-maker-backend
    image: nodirshox/habit-maker-backend:latest
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - BACKEND_API=${BACKEND_API}
    ports:
      - "6001:4000"
volumes:
  habit-db:
    driver: local
